From ubuntu_utopic_ssh:latest
MAINTAINER samsun <sam@ptthink.com>

# Install Erlang
RUN apt-get update
RUN apt-get install -y erlang-base
RUN apt-get install -y erlang-tools
RUN apt-get install -y erlang-parsetools
RUN apt-get install -y erlang-inets
RUN apt-get install -y erlang-ssl
RUN apt-get install -y erlang-eunit
RUN apt-get install -y erlang-dev
RUN apt-get install -y erlang-xmerl
RUN apt-get install -y erlang-src

